name: "CI"

on:
  pull_request:

permissions:
  contents: read

jobs:
  check-dependencies:
    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x, 20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install --immutable --immutable-cache --check-cache
